var youtubeLinks = [
    "https://www.youtube.com/watch?v=aYsgsSo1aow", //Ghost Astley Tokyo
    "https://www.youtube.com/watch?v=7t5CfmS0UuY", //How to put your mouse on the table
    "https://www.youtube.com/watch?v=EPNr4aztjX8", //How to left click
    "https://www.youtube.com/watch?v=SNvDUO42Hys", //phoon too much for zblock
    "https://www.youtube.com/watch?v=czTksCF6X8Y", //Pizza Time
    "https://www.youtube.com/watch?v=gRMNwrNk5WE", //Joe many liberals
    "https://www.youtube.com/watch?v=gkTb9GP9lVI", //Troll song
    "https://www.youtube.com/watch?v=D-GU4jvSvz4", //Triage at Dawn
    "https://www.youtube.com/watch?v=geNMz0J9TEQ", //Meet the Scout
    "https://www.youtube.com/watch?v=zNZ1rq5kW4M", //A Tribute to Minecraft
    "https://www.youtube.com/watch?v=iijdWiQppq0", //Forest Maze
    "https://www.youtube.com/watch?v=WqsQ2zIsTYk", //Monke Need to Swing
    "https://www.youtube.com/watch?v=VqB1uoDTdKM", //Door Stuck
    "https://www.youtube.com/watch?v=wJWksPWDKOc", //EATEOT
    "https://www.youtube.com/watch?v=vIKbbBIK9_s", //new phone
    "https://www.youtube.com/watch?v=hT116E2W2JQ", //DeSinc Webcam
    "https://www.youtube.com/watch?v=sIj3TFlI9o8", //ANOMALY AUSCHWITZ
    "https://www.youtube.com/watch?v=wcR36N3SM7Q", //Off to visit your mother
    "https://www.youtube.com/watch?v=861-pxjkokk", //Completely normal revolver
    "https://www.youtube.com/watch?v=PFkju1-0lZI", //GMOD KINECT
    "https://www.youtube.com/watch?v=HV1O9TaK_qg", //Gorilla tag Trailer
    "https://www.youtube.com/watch?v=j2MnNBE9j-w", //Is that a flying fish?
    "https://www.youtube.com/watch?v=NgFHgVLC-Y0", //Step and go Heavy
    "https://www.youtube.com/watch?v=chpmONLYjzQ", //He just kept on yoing
    "https://www.youtube.com/watch?v=p5L9-k0uV2A", //Pet Russian
    "https://www.youtube.com/watch?v=zrHwZrfp3MY", // VTOL VR has a beautiful and complex control scheme
    "https://www.youtube.com/watch?v=1nCqRmx3Dnw", //Fresh Prince
    "https://www.youtube.com/watch?v=ngORPZj4wwY", //I'm going to die
    "https://www.youtube.com/watch?v=gm9lE97sIJo", //301MPH DeSinc
    "https://www.youtube.com/watch?v=ym_mNU6DWK8", //Art in reload animations
    "https://www.youtube.com/watch?v=VqeMjHmL9eg", //Titanfall 2 Intro Cinematic
    "https://www.youtube.com/watch?v=dy5xLVx2NGY", //What To Do If Your Parachute Fails
    "https://www.youtube.com/watch?v=_YYEcBZOZ7Q", //holy shit is he stuck in camera?
    "https://www.youtube.com/watch?v=HmZm8vNHBSU", // Anti piracy lol
    "https://www.youtube.com/watch?v=LZgeIReY04c", //Never illegally download
    "https://www.youtube.com/watch?v=tGoVKaLXsjk", //another marine joke
    "https://www.youtube.com/watch?v=Vt3dGuQahU0", //don't worry it's unloaded
    "https://www.youtube.com/watch?v=a8uyilHatBA", //r u ok elon?
    "https://www.youtube.com/watch?v=7uAaq6qa_D4", //ITSSS YOUR BIRRTHHDAYYY TODAYYYY
    "https://www.youtube.com/watch?v=SKt1GtGPv_0", //hApPy BiRtHdAy - In Da Club!!!
    "https://www.youtube.com/watch?v=9ZEURntrQOg", //Happy together
    "https://www.youtube.com/watch?v=WbRn0jzBXWM", //Gman clears up a common misconception
    "https://www.youtube.com/watch?v=ZSrvJ4Wfx2w", //tf2's diverse complexities Funke
    "https://www.youtube.com/watch?v=uzq7iDhIg_k", //never taunt when killing a spy
    "https://www.youtube.com/watch?v=bMVN1Gq5a4U", //New vegas speech check
    "https://www.youtube.com/watch?v=PXqcHi2fkXI", //You've been trolled
    "https://www.youtube.com/watch?v=7qhi6TW2Jfk", //burgeria.mp4
    "https://www.youtube.com/watch?v=v3HaQ3Fw25o", //Scott the woz gets punched
    "https://www.youtube.com/watch?v=UCQk34MD5zc", //Medic gang
    "https://www.youtube.com/watch?v=6yUKtPIRa5M", //Jerma shuts off his pc
    "https://www.youtube.com/watch?v=Iu5CqAE9cGU", //You can't do that
    "https://www.youtube.com/watch?v=6a_9HQW1VmY" //Demonetized Again Funke
];

var randomItem = youtubeLinks[Math.floor(Math.random()*youtubeLinks.length)];
document.getElementById('trolled').href = randomItem